# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: GatewayD docs
email: docs@gatewayd.io
description: >- # this means to ignore newlines until "baseurl:"
  GatewayD is a cloud-native database gateway for building data-driven applications. This documentation will help you get started with GatewayD.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gatewaydio
github_username: gatewayd-io
logo: /assets/gatewayd-logotype-light.png

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed
  - jekyll-redirect-from

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.4"

heading_anchors: true
permalink: /:slugified_categories/:title

callouts:
  wip:
    title: üöß Work in Progress
    color: yellow
  note:
    title: üóíÔ∏è Note
    color: blue
  warning:
    title: ‚ö†Ô∏è Warning
    color: yellow

aux_links:
  GitHub:
    - "https://github.com/gatewayd-io/docs"
  Twitter:
    - "https://twitter.com/gatewaydio"
  Linkedin:
    - "https://www.linkedin.com/company/gatewayd/"
  # Email:
  #   - "mailto:docs@gatewayd.io"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - vale.ini
  - Makefile
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

footer_content: "¬© 2023 GatewayD Labs."
last_edit_timestamp: true
last_edit_time_format: "%A %e %b %Y at %I:%M %p"
gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub."
gh_edit_repository: "https://github.com/gatewayd-io/docs"
gh_edit_branch: "main"
gh_edit_view_mode: "edit"
